/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop;

import java.awt.Font;
import petshop.telas.cadastro.TelaCadastraClientes;
import petshop.relogio.JLabelTime;
import petshop.telas.listar.TelaListarTodos;

/**
 *
 * @author 28233708
 */
public class PetShopView extends javax.swing.JFrame {

    /**
     * Creates new form PetShopView
     */
    public PetShopView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        JLabelTime relogio = new JLabelTime();
        JLabelTime tmpRelogio = new JLabelTime();
        tmpRelogio = relogio;
        Font f = new Font("Gabriola", Font.BOLD, 50);
        tmpRelogio.setFont(f);
        tmpRelogio.setBounds(0,0,300,50);
        jPanelRelogio.add(tmpRelogio);
          
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelDesktop = new javax.swing.JPanel();
        btnJDeskCadastro = new javax.swing.JButton();
        jPanelRelogio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemAlterarCliente = new javax.swing.JMenuItem();
        jMenuItemExcluirCliente = new javax.swing.JMenuItem();
        jMenuItemPesquisarCliente = new javax.swing.JMenuItem();
        jMenuAnimais = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuVeterinarios = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuHistoricos = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanelDesktop.setPreferredSize(new java.awt.Dimension(920, 520));

        btnJDeskCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/img/icones/icones/Users.png"))); // NOI18N
        btnJDeskCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJDeskCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRelogioLayout = new javax.swing.GroupLayout(jPanelRelogio);
        jPanelRelogio.setLayout(jPanelRelogioLayout);
        jPanelRelogioLayout.setHorizontalGroup(
            jPanelRelogioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanelRelogioLayout.setVerticalGroup(
            jPanelRelogioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDesktopLayout = new javax.swing.GroupLayout(jPanelDesktop);
        jPanelDesktop.setLayout(jPanelDesktopLayout);
        jPanelDesktopLayout.setHorizontalGroup(
            jPanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesktopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnJDeskCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDesktopLayout.createSequentialGroup()
                .addContainerGap(752, Short.MAX_VALUE)
                .addComponent(jPanelRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDesktopLayout.setVerticalGroup(
            jPanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesktopLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanelRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJDeskCadastro)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanelDesktop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jMenuClientes.setText("Clientes");

        jMenuItemCadastrarCliente.setText("Cadastrar novo");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemCadastrarCliente);

        jMenuItemAlterarCliente.setText("Alterar");
        jMenuItemAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemAlterarCliente);

        jMenuItemExcluirCliente.setText("Excluir");
        jMenuClientes.add(jMenuItemExcluirCliente);

        jMenuItemPesquisarCliente.setText("Pesquisar cliente");
        jMenuItemPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemPesquisarCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuAnimais.setText("Animais");

        jMenuItem5.setText("Adicionar novo ");
        jMenuAnimais.add(jMenuItem5);

        jMenuItem6.setText("Alterar");
        jMenuAnimais.add(jMenuItem6);

        jMenuItem7.setText("Excluir");
        jMenuAnimais.add(jMenuItem7);

        jMenuItem8.setText("Pesquisar animal");
        jMenuAnimais.add(jMenuItem8);

        jMenuBar1.add(jMenuAnimais);

        jMenuVeterinarios.setText("Veterinários");

        jMenuItem9.setText("Cadastrar");
        jMenuVeterinarios.add(jMenuItem9);

        jMenuItem10.setText("Alterar");
        jMenuVeterinarios.add(jMenuItem10);

        jMenuItem11.setText("Excluir");
        jMenuVeterinarios.add(jMenuItem11);

        jMenuItem12.setText("Perquisar veterinário");
        jMenuVeterinarios.add(jMenuItem12);

        jMenuBar1.add(jMenuVeterinarios);

        jMenuHistoricos.setText("Históricos");

        jMenuItem13.setText("Criar histórico de um novo animal");
        jMenuHistoricos.add(jMenuItem13);

        jMenuItem14.setText("Adicionar no histórico do animal");
        jMenuHistoricos.add(jMenuItem14);

        jMenuItem15.setText("Exibir histórico do animal");
        jMenuHistoricos.add(jMenuItem15);

        jMenuBar1.add(jMenuHistoricos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(963, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarClienteActionPerformed

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastraClientes telaCadastra = new TelaCadastraClientes();
        jDesktopPane1.add(telaCadastra);
        telaCadastra.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void btnJDeskCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJDeskCadastroActionPerformed
        // TODO add your handling code here:
        TelaCadastraClientes telaCadastra = new TelaCadastraClientes();
        jDesktopPane1.add(telaCadastra);
        telaCadastra.setVisible(true);
    }//GEN-LAST:event_btnJDeskCadastroActionPerformed

    private void jMenuItemPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarClienteActionPerformed
        // TODO add your handling code here:
        TelaListarTodos telaListar = new TelaListarTodos();
        jDesktopPane1.add(telaListar);
        telaListar.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJDeskCadastro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAnimais;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuHistoricos;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAlterarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemExcluirCliente;
    private javax.swing.JMenuItem jMenuItemPesquisarCliente;
    private javax.swing.JMenu jMenuVeterinarios;
    private javax.swing.JPanel jPanelDesktop;
    private javax.swing.JPanel jPanelRelogio;
    // End of variables declaration//GEN-END:variables
}
