/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.telas.listar;

import bean.clientes.ClientesDAO;
import bean.clientes.ClientesVO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz-PC
 */
public class TelaListarTodos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListarTodos
     */
    public TelaListarTodos() {
        initComponents();
        preencherTabela();
    }
    
    public void preencherTabela(){
        ArrayList dados = new ArrayList();
       String [] colunas = new String[]
        {"CÓDIGO","TIPO","NOME","SEXO","RG","CPF",
         "CEP","ENDEREÇO","N°","TELEFONE","CELULAR","EMAIL"};
        
        ClientesDAO dao = new ClientesDAO();
        
        try{
         for(ClientesVO c : dao.listarTodos()){
             dados.add(new Object[]{
                 c.getCod(),
                 c.getTipo(),
                 c.getNome(),
                 c.getSexo(),
                 c.getRg().getRg(),
                 c.getCpf().getCpf(),
                 c.getCep().getCep(),
                 c.getCep().getEndereco(),
                 c.getNum_resid(),
                 c.getTelefone(),
                 c.getCelular(),
                 c.getEmail()
             });
         }
          ModeloTabela modelo = new ModeloTabela(dados, colunas); 
          tblCliente.setModel(modelo);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro ao preencher a tabela "
                    + ex + JOptionPane.ERROR_MESSAGE);
        }
      
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("LISTAR TODOS CLIENTES");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setResizable(false);
            tblCliente.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
